context:
  version: 2.0.0

package:
  name: remark-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/remark-language-server/-/remark-language-server-${{ version }}.tgz
  sha256: bbcbfbd25769df496df0091ca012cba146f490c17f120289cdb5b69046a87b84

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - remark-language-server 2>&1 | grep -q 'Connection input stream is not set.'

about:
  license: MIT
  license_file:
    - license
    - third-party-licenses.txt
  summary: A language server to lint and format markdown files with remark
  homepage: https://github.com/remarkjs/remark-language-server
  repository: https://github.com/remarkjs/remark-language-server

extra:
  recipe-maintainers:
    - danielnachun
